### ISSUE TITLE
coordinate information

### ISSUE THREAD

**Issue by zhumanli** [ma-xu/Context-Cluster#1]
Hi,

Thank you very much for such great work! I'm wondering why the position information, i.e. coordinates, is important? And what motivates you to combine it with the channel (i.e. color)?

**Comment by ma-xu** [comment]
Hi Thanks for your interest. 
1. Without positional information, we cannot know where the pixel or point is if we view an image as unorganized points. Position is also an important information used by conv implicitly and used by ViTs explicitly.
2. It is a common and easy practice as we presented in the work. More better designs can be explored and that will be one our future work.

**Comment by zhumanli** [comment]
Thanks a lot for your quick reply and explanation.

By the way, do you think the proposed method can be used for object keypoints detection?

**Comment by ma-xu** [comment]
Sure, it is a genreal visual representation method. BTW, the performance may not as strong as sota methods.

**Comment by zhumanli** [comment]
Thank you so much for the discussion.
