### ISSUE TITLE
Running error when run the pointcloud demo.

### ISSUE THREAD

**Issue by yuan-zm** [ma-xu/Context-Cluster#10]
Thanks for your great work.
 
You may forget to upload the code of PointNet model or PointMLP model.

The running error is 

```
net = models.__dict__[args.model](num_classes=args.num_classes)
KeyError: 'PointNet'
```

**Comment by ma-xu** [comment]
@dream-toy Thanks for your interest. Just double-checked, looks like we dont need PointNet. Could you please try again?

`python main.py --model pointMLP_CoC --msg demo`

**Comment by yuan-zm** [comment]
Thank you for your quick reply. It works now.
