### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by shixishi** [ma-xu/Context-Cluster#11]
class PointRecuder(nn.Module):
    """
    Point Reducer is implemented by a layer of conv since it is mathmatically equal.
    Input: tensor in shape [B, C, H, W]
    Output: tensor in shape [B, C, H/stride, W/stride]
    """

    def __init__(self, patch_size=16, stride=16, padding=0,
                 in_chans=3, embed_dim=768, norm_layer=None):
        super().__init__()
        patch_size = to_2tuple(patch_size)
        stride = to_2tuple(stride)
        padding = to_2tuple(padding)
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size,
                              stride=stride, padding=padding)
        self.norm = norm_layer(embed_dim) if norm_layer else nn.Identity()

    def forward(self, x):
        x = self.proj(x)
        x = self.norm(x)
        return 

The dimension of the output written in the comment seems to be inconsistent with the one in the code, I checked the code and the output dimension in the code is 
[B, embed_dim, H/stride, W/stride], not is the [B, C, H/stride, W/stride].
I hope the author can answer this question, thanks！

**Comment by ma-xu** [comment]
Sry I didn't understand your question. "embed_dim" and "C" share same meaning, the number of channels.

**Comment by shixishi** [comment]
> Sry I didn't understand your question. "embed_dim" and "C" share same meaning, the number of channels.

I mean that the number of input channels and the number of output channels are different. But the code comments use the same symbol for both input and output channels, so I think the number of input and output channels are equal.

**Comment by ma-xu** [comment]
Ohhh, got it. Let me update the comments now. Thanks for the kind reminder.
----
Done. Feel free to let me know if you have any other questions or concerns. Thanks for the detailed question.
