### ISSUE TITLE
the code question

### ISSUE THREAD

**Issue by shixishi** [ma-xu/Context-Cluster#12]
Traceback (most recent call last):
  File "/home/std/Context-Cluster/cluster_visualize.py", line 176, in <module>
    main()
  File "/home/std/Context-Cluster/cluster_visualize.py", line 124, in main
    load_checkpoint(model, args.checkpoint, True)
  File "/home/std/anaconda3/lib/python3.9/site-packages/timm/models/helpers.py", line 75, in load_checkpoint
    incompatible_keys = model.load_state_dict(state_dict, strict=strict)
  File "/home/std/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ContextCluster:
        Unexpected key(s) in state_dict: "fea_pos". 

RuntimeError: Error(s) in loading state_dict for ContextCluster:
        Unexpected key(s) in state_dict: "fea_pos". 
I'm having this problem when I run the cluster_visualize.py.
Thanks to the author for answering the questions！

**Comment by ma-xu** [comment]
You can try the coc_tiny_plain, checkpoint here: https://web.northeastern.edu/smilelab/xuma/ContextCluster/checkpoints/coc_tiny_plain/coc_tiny_plain.pth.tar in the README.md.

The reason of this error is that we slightly re-organized the code for faster training and inference. We are working on re-training all models and update the links.

**Comment by TADanton** [comment]
Dear Author,

I tried this checkpoint with model=coc_tiny and imagenet dataset. However, the output is only Acc@1 54.540 (45.460) Acc@5 79.116 (20.884). May I ask whether I may have done something wrong?

Thanks a lot for any possible help in advance!

**Comment by ma-xu** [comment]
@TADanton I assume there is some bugs during your inference maybe?

BTW, we update our codes and checkpoints, with slightly improvements. Mainly two updates: 1) fix a bug mask.sum to sim.sum; 2) conv1x1 to Linear implementation.

**Comment by ma-xu** [comment]
@shixishi Thanks for your patience. The updated checkpoints are updated, with slightly improvements. Mainly two updates: 1) fix a bug mask.sum to sim.sum; 2) conv1x1 to Linear implementation.

**Comment by ma-xu** [comment]
Closed no further discussions. Feel free to reopen it if any further questions.
