### ISSUE TITLE
Is it possible to "reverse" the clustering process as a decoding?

### ISSUE THREAD

**Issue by huanglianghua** [ma-xu/Context-Cluster#13]
Hi, @ma-xu , congrats on your amazing work!

I wonder if it is possible to reverse the clustering process of ContextCluster to facilitate dense prediction and even generative tasks?

**Comment by jackhu-bme** [comment]
Me too. Expecting new work on "decoder" for generative tasks. If the work is already done, please give us links to it.

**Comment by jackhu-bme** [comment]
The clustering-based encoder-decoder could be really beneficial to areas when clustering and manipulating of clusters are needed in the generation process, including where I'm doing research in.

**Comment by ma-xu** [comment]
@huanglianghua @Jack-Hu-2001 Thanks for your insightful discussions, and sorry for the late reply since I was busy previously. 

The idea is interesting and very novel. We would be happy to work on that in the future!

**Comment by ma-xu** [comment]
Closed no further discussions. Feel free to reopen it if any further questions.
