### ISSUE TITLE
Model Question

### ISSUE THREAD

**Issue by Joazs** [ma-xu/Context-Cluster#14]
Hello, what is the effect of context cluster on small target segmentation? Is it suitable for small target segmentation? When I segmented small targets, I found that the effect was average. How can I improve it?

**Comment by ma-xu** [comment]
Hi @Joazs, Sorry for the late reply since I was busy previously. 

For small targets, I think you may need more centers/clusters, simplying update the proposal_w and proposal_h with greater values, and fine-tuning the model. More  centers will focus more tiny  objects, but will more computations.

**Comment by Joazs** [comment]
I still don't understand. If more clustering centers are needed, it is more important to reduce the values of proposals_ w and proposal_ h?

**Comment by ma-xu** [comment]
@Joazs we consider clustering centers  = proposals_w * proposal_h. Help this can help. Feel free to let me know if you have any further questions.

**Comment by ma-xu** [comment]
Closed no further discussions. Feel free to reopen it if any further questions.
