### ISSUE TITLE
Can not load the pre-trained model.

### ISSUE THREAD

**Issue by yuan-zm** [ma-xu/Context-Cluster#16]
Hi @ma-xu ,

I want to use Context-Cluster to do some down-stream tasks. However, I find that I can not load you provide pre-trained model. This may caused by the MLP layer https://github.com/ma-xu/Context-Cluster/blob/c307ab19a79eff737499e24946d08b84f6f30485/models/context_cluster.py#L188.

When will you upload the new pre-trained model?

**Comment by ma-xu** [comment]
@dream-toy Thanks for your interest. We will release new checkpoint by the end of this month due to limited computational resources.

**Comment by yuan-zm** [comment]
ok, Thank you.

**Comment by DengFlagellants** [comment]
You can modify a few variable names in the Cluster class of context_cluster.py. self.f -> self.fc1 self.proj -> self.fc2 self.v -> self.fc_v

**Comment by ma-xu** [comment]
@dream-toy @DengFlagellants 

Thanks for your patience. The updated checkpoints are updated, with slightly improvements. Mainly two updates: 1) fix a bug mask.sum to sim.sum; 2) conv1x1 to Linear implementation.

**Comment by ma-xu** [comment]
Closed no further discussions. Feel free to reopen it if any further questions.
