### ISSUE TITLE
Meet problems when loading checkpoint

### ISSUE THREAD

**Issue by ZilingLiu** [ma-xu/Context-Cluster#17]
![image](https://user-images.githubusercontent.com/103492403/234851855-3309d6e8-095d-4202-b113-ad77985e5305.png)
I met some problems when loading checkpoint. It seems that there is no norm0, norm2, norm4, norm6 in checkpoint and the fea_pos, norm.weight, norm.bias, head.weight, head.bias in the checkpoint seems not be used in model.

**Comment by ma-xu** [comment]
Thanks. See here https://anonymous.4open.science/r/ContextCluster/README.md 
We slightly re-organized the codes for faster training/inference.
We will update the checkpoints after mid of May.

**Comment by ZilingLiu** [comment]
Thanks for your reply!

**Comment by ma-xu** [comment]
@SUSTech-lzl 

Thanks for your patience. The updated checkpoints are updated, with slightly improvements. Mainly two updates: 1) fix a bug mask.sum to sim.sum; 2) conv1x1 to Linear implementation.

**Comment by ma-xu** [comment]
Closed no further discussions. Feel free to reopen it if any further questions.
