### ISSUE TITLE
The meaning of self.end_indices = [0, 2, 4, 6]

### ISSUE THREAD

**Issue by LuPaoPao** [ma-xu/Context-Cluster#18]
Thank you for your outstanding contribution. 
What is the meaning of this(self.end_indices = [0, 2, 4, 6]) ? 
Should this parameter be modified if the number of blocks contained in each of the 4 stages changes?

**Comment by ma-xu** [comment]
@LuPaoPao Thanks for your interest.

This setting is used to identify the output of each stage (for mmdetection adn mmsegmentation) 

No, you dont need to.
