### ISSUE TITLE
Dimensional problem during the Validation.

### ISSUE THREAD

**Issue by sky123CT** [ma-xu/Context-Cluster#19]
Hi, Thank you very much for your contribution. Your works are very attractive.

**Comment by sky123CT** [comment]
But during the validation of srgementation. There are some Dimensional problem when I try to load the model checkpoint you provide, namely Coc_small_49. Could you please provide correct model checkpoint and backbone checkpoint?
<img width="668" alt="Snipaste_2023-05-14_15-21-09" src="https://github.com/ma-xu/Context-Cluster/assets/131677277/493e7b61-d155-409d-94e7-3781e3ecee82">

**Comment by ma-xu** [comment]
@sky123CT Thanks for your interest.

The reson is that the released code change conv1x1 to fc for faster inference. See here: https://github.com/ma-xu/Context-Cluster/issues/2
We will update this by the end of May of early June since I'm busy recently.

**Comment by ma-xu** [comment]
@sky123CT Thanks for your patience. The updated checkpoints are updated, with slightly improvements. Mainly two updates: 1) fix a bug mask.sum to sim.sum; 2) conv1x1 to Linear implementation.

**Comment by sky123CT** [comment]
Thank you so much for your work!
