### ISSUE TITLE
the re-train checkpoints

### ISSUE THREAD

**Issue by woaixueyingying** [ma-xu/Context-Cluster#20]
When can you provide the new training checkpoints?

**Comment by ma-xu** [comment]
@woaixueyingying Thanks for your interest. 
We will update this by the end of May of early June since I'm busy recently.

**Comment by woaixueyingying** [comment]
OK,thanks.I am looking forward to it.

**Comment by ma-xu** [comment]
@woaixueyingying Thanks. Once updated, we will let you know.

**Comment by ma-xu** [comment]
@woaixueyingying Thanks for your patience. The updated checkpoints are updated, with slightly improvements. Mainly two updates: 1) fix a bug mask.sum to sim.sum; 2) conv1x1 to Linear implementation.

**Comment by woaixueyingying** [comment]
Trank you

**Comment by ma-xu** [comment]
Closed. Please feel free to re-open it if any further questions or concerns.
