### ISSUE TITLE
question about the forward embedding

### ISSUE THREAD

**Issue by wangren97** [ma-xu/Context-Cluster#22]
Dear author,

Thanks for your nice work! I have a question about the forward_embedding function in [context_cluster.py](https://github.com/ma-xu/Context-Cluster/blob/main/models/context_cluster.py#L445). In line 445, I think _, c, img_w, img_h = x.shape should be _, c, img_h, img_w = x.shape and when calculating the fea_pos, the order of range_w and range_h should be exchanged in torch.meshgrid.  Is it right?

**Comment by ma-xu** [comment]
Yeah, thanks for your reminder. This will not affect the final result

**Comment by sdu-huanhq** [comment]
> Yeah, thanks for your reminder. This will not affect the final result

Hello, Why does the indexing parameter in `torch.meshgrid` use ij instead of xy in line 450
