### ISSUE TITLE
How can I visualize clustering like paper?

### ISSUE THREAD

**Issue by JihwanEom** [ma-xu/Context-Cluster#3]
Hello, thank you for awesome work!

I want to visualize clusters like figure 4 in paper:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/72460430/225074401-ba60f4db-dba4-434e-9a5e-234b4a4c180a.png">
Could you let me know how can I get visualized maps? 

Thank you!
Jihwan

**Comment by guoyang-xie** [comment]
Same question for visualization. Could you share the code with us? Thanks a lot!

I guess these visualization map should be auto-generated but not hand-written calculated

**Comment by ma-xu** [comment]
@JihwanEom @guoyang-xie Thanks for this issue. I will update a script we used for the visualization by next Tuesday since I'm really busy this week.  This script will automatically generate the clustering results for any selected block and head. Hope that will help you.

**Comment by JihwanEom** [comment]
Sounds great! Thank you for your help.

**Comment by guoyang-xie** [comment]
@ma-xu Thanks for your help! I am looking forward to it!

**Comment by ma-xu** [comment]
@JihwanEom @guoyang-xie 
Thanks for your patience, updated. We re-trained a coc-tiny without region partition and achieved slightly better performance with updated codes, you can download the checkpoints [here](https://web.northeastern.edu/smilelab/xuma/ContextCluster/checkpoints/coc_tiny_plain/coc_tiny_plain.pth.tar).
Then, simply run the following code:
```
python cluster_visualize.py --image {path_to_image} --model {model} --checkpoint {path_to_checkpoint} --stage {stage} --block {block} --head {head}
```

The generated image will be saved to images/cluster_vis/{model}. 

We also provide some generated images in the `images/cluster_vis/coc_tiny_plain_SomeGoodExamples` folder.

We will update more checkpoints later (you can also train different models/settings and using this script to get generated images).

**Comment by guoyang-xie** [comment]
Thanks a lot! I will follow that later.

**Comment by JihwanEom** [comment]
Thanks! I'll enjoy this :)
