### ISSUE TITLE
Link to download weights is broken

### ISSUE THREAD

**Issue by HussainAlasmawi** [ma-xu/Context-Cluster#33]
I tried to download the model weights from the provided link and got the following error: The requested URL /smilelab/xuma/ContextCluster/coc-updates/tiny/ was not found on this server. I hope you'll be able to fix this issue soon.

Thanks

**Comment by ma-xu** [comment]
Hi,thanks for letting me know. Currently, our lab's website has been shutted down. We have contacted with the manager, hope it will be fixed soon. Please let me know if it is still not working after one week, thanks!

**Comment by HussainAlasmawi** [comment]
Hello,

Still the server is down.

**Comment by ma-xu** [comment]
@HussainAlasmawi Got it. Okay, let me retry the models. It may take some time. Once done, I will later you know. If want a particular checkpoint, please let me know and I can train it for you first.

**Comment by HussainAlasmawi** [comment]
I need the three models  Tiny, Small, & Medium. Hope it does not take that long.

Thanks,

**Comment by HussainAlasmawi** [comment]
@ma-xu would like to know how long it will take to get the models.

**Comment by ma-xu** [comment]
@HussainAlasmawi  I will check tmr. I think Tony and small are done.

**Comment by ma-xu** [comment]
@HussainAlasmawi 
Just checked, the tiny and tiny_plain are done, achieves  **73.2%** and **73.8%** top-1 accuracy, which is higher than reported (71.9 and 72.0).  I upload the checkpoints and logs in the google drive link:

https://drive.google.com/drive/folders/13MHhDnITaqcsKiSGeUZPeJ-VpfQkH_9F?usp=sharing


Once small and mid are finished, I will uploade to the link and ping you. 
Thanks for your patience, please let me know if you have any questions.

**Comment by HussainAlasmawi** [comment]
Great!!

Thanks

**Comment by ma-xu** [comment]
@HussainAlasmawi Hi, I also uploaded the small model, which achieves 78.1, 0.3 higher than reported.

Sry that the training cost too much time since my nodes are limited and preemptible. I will update medium once finshed.

**Comment by ma-xu** [comment]
@HussainAlasmawi Updated all checkpoints and the README file, thanks for your kind reminder.
