### ISSUE TITLE
Can't reproduce visualization result

### ISSUE THREAD

**Issue by HieuBui99** [ma-xu/Context-Cluster#37]
Hello. Thanks for your great work!

I'm trying to play around with the visualization, but can't seem to reproduce the result in your example folder.
 
I just cloned the repository, downloaded the weight and ran the below command.
```
python cluster_visualize.py --image images/A.JPEG --model coc_tiny_plain --checkpoint model_best.pth.tar --stage 0 --block 0 --head 1
```

Result: 
![image](https://github.com/ma-xu/Context-Cluster/assets/35796698/3c637fd3-1f1b-408b-b24b-9d768b71e840)

Compared to the example;
![image](https://github.com/ma-xu/Context-Cluster/assets/35796698/3935deaa-0086-4fc4-afdc-77f933291880)

**Comment by potatochip1211** [comment]
@HieuBui99 I have the same problem.Have you solved it?

**Comment by potatochip1211** [comment]
@HieuBui99 I guess I got the anwser.The key is _--shape_ parameter which isn't actually play a role in  cluster_visualize.py. I can't find _args.shape_ in it. There is a downsample step before test in the line 120 linked to __def _preprocess()_. The original downsample size is (224,224) that may don't match other images whose weights are not equal to height. So, I try to modify the downsample size to (375, 500) that is the size of the A.jpeg. Here are some results I've tried, which is more accurate but there are some differences with example images. I think different downsample size would make different. 
new: (375,500)
![A_Stage0_Block0_Head3](https://github.com/ma-xu/Context-Cluster/assets/97969505/017f03e4-2af7-42a8-8685-9632b6f7262a)
before: (224,224)
![image](https://github.com/ma-xu/Context-Cluster/assets/97969505/761ea47c-30d8-43b2-a33b-a51b154be47e)

**Comment by ma-xu** [comment]
Hi @HieuBui99 @hmqbeauty Thanks for your interest!
try this:
python cluster_visualize.py --image images/A.JPEG --model coc_tiny_plain --checkpoint model_best.pth.tar --stage 0 --block 2 --head 0

in most heads, the clustering results are not very clear, as also indicated in the paper. In the retrained model, stage 0 block 2 head 0 will give very similar results in the paper (the differences are from 1. we fixed a small bug in the original model; 2. we retrained the model achieving better cls. acc.). 

Meanwhile, I also updated all visualization results of all the blocks / heads in the first stage:
https://drive.google.com/drive/folders/1x1dSZSoXd86SceyJsBUSiV4bRuqr2BuK?usp=sharing

Please let me knowv if you have any questions or concerns. 
![A_Stage0_Block2_Head0](https://github.com/ma-xu/Context-Cluster/assets/6723062/bd97b8a7-adad-4633-8a63-d95defbb5aa8)

**Comment by HieuBui99** [comment]
Thank you for your answer. It looks much better now.
