### ISSUE TITLE
Similarity in code differs from paper? 

### ISSUE THREAD

**Issue by iumyx2612** [ma-xu/Context-Cluster#4]
In the paper, Context Clustering is as follow:
- Create $P_s$ from input points $P$: it is [`x = self.f(x)`](https://github.com/ma-xu/Context-Cluster/blob/main/models/context_cluster.py#L136) right? 
- Then centers are created by applying `AdaptiveAvgPooling` on $P_s$ which is `x`, it is [`center`](https://github.com/ma-xu/Context-Cluster/blob/main/models/context_cluster.py#L148) right?
- Then `sim` should be calculated using [`pairwise_cos_sim`](https://github.com/ma-xu/Context-Cluster/blob/main/models/context_cluster.py#L92) (according to paper), but in [line 151](https://github.com/ma-xu/Context-Cluster/blob/main/models/context_cluster.py#L151), `sim` is calculated as $sig(\alpha s_i + \beta)$

**Comment by ma-xu** [comment]
It is same as paper. Cos similarity is s_i. Please check Eq1 and Eq2 in the paper.

**Comment by iumyx2612** [comment]
> It is same as paper. Cos similarity is s_i. Please check Eq1 and Eq2 in the paper.

The paper stated that: "We then calculate the pair-wise cosine similarity matrix $S ∈ R^{c \times n}$ between $P_s$ and the resulting set of center points", and "the similarity between the $m$ points and the center is $s ∈ R^m$ (a subset in $S$)". So the similarity $s$ should be calculated using [`pairwise_cos_sim`](https://github.com/ma-xu/Context-Cluster/blob/main/models/context_cluster.py#L92) no?

**Comment by ma-xu** [comment]
s is calculated using pairwise_cos_sim. Feel free to double-check the code and paper, they are aligned.

**Comment by iumyx2612** [comment]
> s is calculated using pairwise_cos_sim. Feel free to double-check the code and paper, they are aligned.

It is, I'm sorry for causing this stupid trouble
