### ISSUE TITLE
Question for the implementation of feature aggregation.

### ISSUE THREAD

**Issue by peterzpy** [ma-xu/Context-Cluster#8]
Hi, I wonder why you implemented the feature aggregation using the new feature 'value', but not the original feature 'x' that calculated the similarity matrix. Since it may cause a collapse or anything else? Waiting for your response :)

**Comment by ma-xu** [comment]
Hi, thanks for the question. There should be no big differences in terms of performance. I didn't see a particular reason to get a trivial solution or feature collapse.

**Comment by peterzpy** [comment]
Thanks for your reply.
